title: Brad Seeley
description: Engineering & Professional portfolio
show_downloads: false
remote_theme: pages-themes/modernist@v0.2.0

github:
  is_project_page: false

#theme: architect
#remote_theme: pages-themes/architect@v0.2.0

#theme: cayman
#remote_theme: pages-themes/cayman@v0.2.0

#theme: minimal
#remote_theme: pages-themes/minimal@v0.2.0

#theme: modernist
#remote_theme: pages-themes/modernist@v0.2.0

#theme: slate
#remote_theme: pages-themes/slate@v0.2.0

#theme: tactile
#remote_theme: pages-themes/tactile@v0.2.0
